use pinocchio::{
    account::{
        account_content_cast_bytes, account_content_cast_bytes_mut, AccountContent, NewAccountMut,
    },
    entrypoint_v2::ProgramDataParser,
    program_error::ProgramError,
    pubkey::Pubkey,
};
use pinocchio_macro::entrypoint;

//- #[derive(PartialEq, Eq, ProgramDataParser)]
#[derive(PartialEq, Eq)]
#[repr(u8)]
enum Instruction {
    NewUser = 1,
}

#[derive(Debug)]
#[repr(C)]
struct User {
    id: u8,
}

entrypoint! {
    instruction_type: Instruction,
    program_id: program_id;

    Instruction::NewUser => |
        user: NewAccountMut<User>;
        name: &str,
    |,
}

fn new_user(_program_id: &Pubkey, _user: NewAccountMut<User>, _name: &str) {
    todo!()
}

fn main() {
    println!("OK");
}

// -- Instances below should be autogenerated in the future. --

impl<'data> ProgramDataParser<'data> for Instruction {
    type Error = ProgramError;

    fn parse(data: &'data [u8]) -> Result<(Self, &'data [u8]), Self::Error>
    where
        Self: Sized + 'data,
    {
        let Some((&instruction, data)) = data.split_first() else {
            return Err(ProgramError::InvalidInstructionData);
        };

        let instruction = match instruction {
            1 => Self::NewUser,
            _ => return Err(ProgramError::InvalidArgument),
        };

        Ok((instruction, data))
    }
}

// SAFETY: All accounts use same length discriminators and they are all unique.
unsafe impl AccountContent for User {
    const DISCRIMINATOR: &'static [u8] = &[1];

    type AsContent<'data> = &'data Self;

    unsafe fn content<'data>(data: &'data [u8]) -> Self::AsContent<'data> {
        // SAFETY: `User` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { account_content_cast_bytes::<Self>(data) }
    }

    type AsContentMut<'data> = &'data mut Self;

    unsafe fn content_mut<'data>(data: &'data mut [u8]) -> Self::AsContentMut<'data> {
        // SAFETY: `User` is `#[repr(C)]` and can be constructed from its bytes.
        unsafe { account_content_cast_bytes_mut::<Self>(data) }
    }
}
