use core::pin::Pin;

use crate::pubkey::Pubkey;

/// Accounts consist of a set of properties common to all accounts, and bytes that need additional
/// interpretation, depending on the account type.
///
/// This trait covers common properties that are shared by all accounts, when viewed from the
/// standpoint of a program that have received an account as one of it's inputs.
///
/// This trait applies to cases when an account is being interacted with "directly" - for example,
/// via an [`&Account`] reference.  When interaction requires locking, as in the case of the
/// [`AccountMutRef`], [`AccountCommonRef`] should be used.
///
/// This trait covers the immutable interaction.  Accounts that can be modified, as determined by
/// their type (such as [`Pin<&mut Account<T>>`]) implement [`AccountCommonMut`] for mutating their
/// common properties.
pub trait AccountCommon {
    fn is_signer(&self) -> bool;

    fn is_writable(&self) -> bool;

    fn is_executable(&self) -> bool;

    fn resize_delta(&self) -> i32;

    fn address(&self) -> &Pubkey;

    fn owner(&self) -> &Pubkey;

    fn lamports(&self) -> u64;

    fn data_len(&self) -> u64;
}

/// Covers mutation of the common properties for accounts that do not require locking.
/// This is a companion trait to [`AccountCommon`].
///
/// # Data length and data bytes
///
/// I think `resize_delta` and `data_len` fields should not be directly modifiable on all accounts,
/// as it makes it possible to cut the data stored in the account, breaking a serialized form of the
/// value stored in there.  Plus `resize_delta` and `data_len` should probably be always updated
/// together, even if we are trying to optimize.  And either only along with an update of the
/// contained value, or with some safety check.
///
/// So, in either case, `set_resize_delta()` and `set_data_len()` not part of this trait for mow.
///
/// # `close()` method
///
/// TODO I wonder if this trait should provide a `close()` method.
///
/// TODO In order to close the account, it might be enough to set the `lamports` field to `0`.
/// Currently `AccountInfo::close()` will:
///  - set `resize_delta` to `- <original account data len>`.  This field is ignored by the VM.
///  - set owner to all zeros
///  - set lamports to all zeros
///  - set data length to all zeros
///
/// I do not think that the owner and the data length field matter if the lamports is set to
/// zero, right?  Need to double check what the VM is actually doing here.
pub trait AccountCommonMut {
    fn set_owner(self: Pin<&mut Self>, value: &Pubkey);

    fn set_lamport(self: Pin<&mut Self>, value: u64);
}

// TODO It would be nice to use a macro that provides a common implementation of `AccountCommon` for
// both generic and non generic types.
// The following was generated by Claude, but it does not work.  Macro parser is confused by `tt`,
// saying it is causing an ambiguity, when trying to parse this:
//
// impl_account_common! {
//     impl<T: AccountContent + ?Sized> AccountCommon for Account<T>;
// }
//
// #[macro_export]
// macro_rules! impl_account_common {
//     (impl(<$($generics:tt)*>)? AccountCommon for $ty:ty $(where $($where_clause:tt)*)? ;) => {
//         impl$(<$($generics)*>)? AccountCommon for $ty $(where $($where_clause)*)? {
//             fn is_signer(&self) -> bool {
//                 self.header.is_signer != 0
//             }
//
//             fn is_writable(&self) -> bool {
//                 self.header.is_writable != 0
//             }
//
//             fn is_executable(&self) -> bool {
//                 self.header.is_executable != 0
//             }
//
//             fn resize_delta(&self) -> i32 {
//                 self.header.resize_delta()
//             }
//
//             fn address(&self) -> &Pubkey {
//                 assert_eq_align!(Pubkey, u8);
//                 &self.header.address
//             }
//
//             fn owner(&self) -> &Pubkey {
//                 assert_eq_align!(Pubkey, u8);
//                 &self.header.owner
//             }
//
//             fn lamports(&self) -> u64 {
//                 self.header.lamports()
//             }
//
//             fn data_len(&self) -> u64 {
//                 self.header.data_len()
//             }
//         }
//     };
// }
//
// I've tried a macro that produces just the method definitions, parametrizing it with "an
// expression to get the header from `self`".  The problem is that if `self` is provided at the call
// site, it is breaking the hygiene, as it is not inside of a method.
//
// The only macro that worked was only parametric by the header field name, as in `($header:ident)
// => ...`.  But, I think, it is not enough?
